"cmp %eax, %ebx\n"
"je equal \n"
"jne notequal\n"
"equal:\n"
"movl $1, %edx\n"
"jmp my_print\n"
"notequal:\n"
"movl $1, %edx\n"
"jmp my_print"
"my_print:\n"
"call printf \n"
"addl $4, %esp\n"
"movl %edx, %esp\n"
"popl %edx\n"
"ret\n"
